# LLDA: scores exatos, múltiplas expressões e correção de viés

Este notebook investiga como transformar **logits da LLM em uma distribuição relativa sobre 54 tópicos**, usando os 2.000 resumos completos do AAPD. O modelo permanece congelado.

Não buscamos apenas respostas válidas: calculamos `log P(expressão + EOS | artigo, prompt)` para **todos os candidatos**, sem poda por beams e sem mascarar ou renormalizar o vocabulário em cada passo.

| Variante | Representação | Correção lexical |
|---|---|---|
| Nome único | Nome canônico de cada classe | Não |
| Nome único corrigido | Mesmo nome canônico | Sim |
| Múltiplas expressões | Três expressões por classe | Não |
| Múltiplas expressões corrigidas | Mesmas três expressões | Sim |

Todas as variantes usam **o mesmo prompt com as 162 expressões**. Isso isola agregação e correção neste ensaio. O notebook anterior de trie usava um prompt com 54 nomes; compará-lo diretamente não isolaria apenas o efeito da poda.

Usamos 400 artigos para escolher a força da correção e 1.600 para avaliação exploratória. Esses 2.000 artigos já foram inspecionados em experimentos anteriores: a divisão atual evita usar os rótulos da avaliação na seleção de lambda, mas **não substitui uma avaliação final em dados novos**.

In [1]:
from pathlib import Path
import sys
import json
import numpy as np
import pandas as pd
import plotly.express as px
from IPython.display import display

ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / 'dataset_loader.py').exists())
EXPERIMENT_DIR = ROOT / 'experimento_classificacao_topicos'
sys.path.insert(0, str(EXPERIMENT_DIR))
from llda_scores_exatos import run, REFERENCES
from verbalizadores_54 import CLASSES, VERBALIZERS, EXPRESSIONS
from llda_trie_54 import require_gpu

pd.set_option('display.max_colwidth', 120)
OUTPUT_DIR = EXPERIMENT_DIR / 'resultados' / 'llda_scores_exatos_54'
CACHE_DIR = None
LOCAL_FILES_ONLY = False
CANDIDATE_BATCH = 24
print(require_gpu())
display(pd.DataFrame({'Classe': CLASSES, 'Expressões': VERBALIZERS}))

{'name': 'NVIDIA GeForce RTX 5080', 'free_bytes': 15727525888, 'total_bytes': 16608133120}

                Classe                                                                                                               Expressões
0               cmp-lg  [Computation and Language (Legacy Category), Computational Language Research (Legacy Category), Language Computation...
1      cond-mat.dis-nn                    [Disordered systems and neural networks, Disordered Neural Systems, Spin Glasses and Neural Networks]
2   cond-mat.stat-mech                                             [Statistical mechanics, Statistical Physics, Statistical Mechanical Systems]
3                cs.AI                                     [Artificial intelligence, AI and Automated Reasoning, Intelligent Reasoning Systems]
4                cs.CC                                   [Computational complexity, Computational Complexity Theory, Complexity of Computation]
5                cs.CE  [Computational engineering finance and science, Scientific and Engineering Computation, Computational Science and Fi...
6                cs.CG                                                      [Computational geometry, Geometric Computing, Geometric Algorithms]
7                cs.CL      [Computational linguistics and natural language processing, Natural Language Processing, Computational Linguistics]
8                cs.CR                                  [Cryptography and security, Cryptographic Security, Computer Security and Cryptography]
9                cs.CV                                       [Computer vision and pattern recognition, Visual Recognition, Image Understanding]
10               cs.CY                                         [Computers and society, Computing and Society, Social Implications of Computing]
11               cs.DB                                                                   [Databases, Database Systems, Data Management Systems]
12               cs.DC                      [Distributed parallel and cluster computing, Distributed Computing, Parallel and Cluster Computing]
13               cs.DL                                              [Digital libraries, Digital Library Systems, Scholarly Digital Collections]
14               cs.DM                                   [Discrete mathematics, Discrete Mathematical Structures, Discrete Mathematical Theory]
15               cs.DS                          [Data structures and algorithms, Algorithms and Data Structures, Algorithm Design and Analysis]
16               cs.FL                            [Formal languages and automata theory, Automata and Formal Languages, Formal Language Theory]
17               cs.GT                                   [Computer science and game theory, Algorithmic Game Theory, Computational Game Theory]
18               cs.HC                                   [Human computer interaction, Human Computer Interfaces, Interactive Computing Systems]
19               cs.IR                                                  [Information retrieval, Search and Retrieval, Retrieval of Information]
20               cs.IT  [Information Theory (Computer Science), Communication Theory (Computer Science), Coding and Information (Computer Sc...
21               cs.LG                                                        [Machine learning, Learning Algorithms, Machine Learning Methods]
22               cs.LO                                          [Logic in computer science, Computational Logic, Formal Verification and Logic]
23               cs.MA                                                [Multiagent systems, Multi Agent Systems, Coordinating Autonomous Agents]
24               cs.MM                                                            [Multimedia, Multimedia Computing, Audio and Video Computing]
25               cs.MS                          [Mathematical software, Software for Mathematical Computation, Mathematical Computing Software]
26               cs.NA    [Numerical Analysis (Computer Science), Numerical Computing (Computer Science), Numerical Methods (Computer Science)]
27               cs.NE                    [Neural and evolutionary computing, Evolutionary and Neural Computation, Neuroevolutionary Computing]
28               cs.NI                              [Networking and internet architecture, Computer Networking, Internet and Network Protocols]
29               cs.PF                                  [Computer performance, Computing Performance Analysis, Performance of Computer Systems]
30               cs.PL                                            [Programming languages, Programming Language Theory, Languages and Compilers]
31               cs.RO                                                                 [Robotics, Robotic Systems, Robot Motion and Navigation]
32               cs.SC                                                 [Symbolic computation, Computer Algebra, Symbolic Algebraic Computation]
33               cs.SE                               [Software engineering, Software Development Engineering, Software Testing and Maintenance]
34               cs.SI                                 [Social and information networks, Social Network Analysis, Information Network Analysis]
35               cs.SY                                              [Systems and control, Control of Dynamical Systems, Systems Control Theory]
36             math.CO                                                         [Combinatorics, Combinatorial Mathematics, Combinatorial Theory]
37             math.IT             [Information Theory (Mathematics), Communication Theory (Mathematics), Coding and Information (Mathematics)]
38             math.LO                                    [Mathematical logic, Mathematical Logic Theory, Logic and Foundations of Mathematics]
39             math.NA                   [Numerical Analysis (Mathematics), Numerical Computing (Mathematics), Numerical Methods (Mathematics)]
40             math.NT                                                         [Number theory, Arithmetic and Number Theory, Theory of Numbers]
41             math.OC                                  [Optimization and control, Mathematical Optimization, Optimal Control and Optimization]
42             math.PR                                                                  [Probability, Probability Theory, Stochastic Processes]
43             math.ST           [Statistics Theory (Mathematics), Mathematical Statistical Theory, Statistical Inference Theory (Mathematics)]
44             nlin.AO                             [Adaptation and self organizing systems, Self Organizing Dynamics, Adaptive Complex Systems]
45     physics.data-an         [Data analysis statistics and probability, Statistical Data Analysis (Physics), Data Analysis Methods (Physics)]
46      physics.soc-ph                                                                      [Physics and society, Social Physics, Sociophysics]
47            q-bio.NC                                                    [Neurons and cognition, Computational Neuroscience, Neural Cognition]
48            q-bio.QM                      [Quantitative methods in biology, Quantitative Biological Methods, Mathematical Methods in Biology]
49            quant-ph                                                        [Quantum physics, Quantum Mechanics, Quantum Information Physics]
50             stat.AP                                                  [Statistics applications, Applied Statistics, Statistical Applications]
51             stat.ME                                            [Statistics methodology, Statistical Methods, Statistical Method Development]
52             stat.ML                                [Statistical machine learning, Statistical Learning Theory, Statistical Learning Methods]
53             stat.TH                      [Statistics Theory (Statistics), Theoretical Statistics, Statistical Inference Theory (Statistics)]

## 1. Score exato: cada token conta uma vez

Para uma expressão tokenizada em $t_1,\ldots,t_m$, o score inclui sua terminação:

$$s(v,x)=\sum_{j=1}^{m+1}\log P(t_j\mid x,t_{<j}),\quad t_{m+1}=\mathrm{EOS}.$$

Usamos *teacher forcing*. O cache do prompt é calculado uma vez por artigo e copiado para os lotes de candidatos. Cada ramo tem seu próprio cache; nenhum candidato recebe tokens de outro. O primeiro token é pontuado pelos logits finais do prompt; os seguintes e EOS são pontuados após consumir os tokens anteriores.

Não dividimos pelo comprimento: a soma preserva a probabilidade da sequência completa. Salvamos os comprimentos para investigar seu efeito. A comparação numérica com teacher forcing sem cache está em `test_scores_exatos.py`.

## 2. Agregar expressões e descontar preferência lexical

Cada classe tem exatamente três expressões manuais e pesos iguais. A agregação usa a média das probabilidades, computada em log-space:

$$S(c,x)=\operatorname{logsumexp}_{v\in V_c}s(v,x)-\log|V_c|.$$

Para a correção, pontuamos as mesmas expressões com três entradas neutras: texto vazio, `N/A` e `Scientific abstract.`. Mantemos o catálogo e as instruções. A referência $b(v)$ é o log da média dessas probabilidades.

$$r(v,x)=s(v,x)-\lambda b(v).$$

Agregamos $r$ no lugar de $s$ na variante corrigida. O resultado é um score baseado em razão de probabilidades; não é mais a probabilidade bruta de gerar a expressão. Escolhemos lambda em `{0, 0.25, 0.5, 0.75, 1}` pelo LRAP dos **400 artigos de validação**, separadamente para nome único e múltiplas expressões.

Entradas neutras são uma aproximação da preferência lexical. O catálogo é inicial e precisa de revisão de domínio: expressões amplas podem abranger mais de uma categoria, e qualificadores não resolvem automaticamente categorias equivalentes.

In [2]:
df, metrics, per_class, distributions = run(
    output_dir=OUTPUT_DIR, cache_dir=CACHE_DIR,
    local_files_only=LOCAL_FILES_ONLY, candidate_batch=CANDIDATE_BATCH,
)
display(metrics.round(4))
print(f'{len(df)} resumos completos pontuados; {len(EXPRESSIONS)} candidatos por artigo')

                         Metodo  lambda   LRAP  Ranking loss  Coverage error  AP micro  Acerto top1  F1 micro top3  F1 macro top3  Jaccard top3
                     nome_unico    0.00 0.2148        0.2736         24.3019    0.0936       0.1219         0.1307         0.1011        0.0832
           nome_unico_corrigido    0.75 0.2684        0.2635         23.8738    0.1362       0.2119         0.1908         0.1772        0.1239
           multiplas_expressoes    0.00 0.2341        0.2656         23.5588    0.1007       0.1362         0.1527         0.1251        0.1013
multiplas_expressoes_corrigidas    1.00 0.3556        0.2131         21.8988    0.2214       0.3738         0.2736         0.2064        0.1817
2000 resumos completos pontuados; 162 candidatos por artigo

                            Metodo  lambda  ...  F1 macro top3  Jaccard top3
0                       nome_unico    0.00  ...         0.1011        0.0832
1             nome_unico_corrigido    0.75  ...         0.1772        0.1239
2             multiplas_expressoes    0.00  ...         0.1251        0.1013
3  multiplas_expressoes_corrigidas    1.00  ...         0.2064        0.1817

[4 rows x 10 columns]

## 3. Distribuição relativa não é probabilidade multi-rótulo calibrada

Para visualizar a distribuição sobre tópicos, aplicamos softmax aos 54 scores:

$$q(c\mid x)=\frac{\exp S(c,x)}{\sum_k\exp S(k,x)}.$$

Essa saída soma 1 e representa **evidência relativa entre as classes**. Um artigo pode ter vários rótulos verdadeiros; portanto, $q$ não estima automaticamente a probabilidade independente de cada rótulo. Também não afirmamos calibração. Nas variantes corrigidas, softmax normaliza scores de razão de probabilidades.

Os CSVs de log-probabilidades brutas, scores agregados e distribuições normalizadas são separados para manter essa distinção.

In [3]:
for method, values in distributions.items():
    assert values.shape == (2000,54)
    assert np.isfinite(values).all()
    np.testing.assert_allclose(values.sum(1), 1, atol=1e-10)
    print(method, '| soma média:', values.sum(1).mean())

example = pd.DataFrame({method: values[0] for method, values in distributions.items()}, index=CLASSES)
print('Artigo:', df.iloc[0].doc_id, '| classes reais:', df.iloc[0].classes_reais_aapd)
display(example.sort_values('multiplas_expressoes_corrigidas', ascending=False).head(12))

nome_unico | soma média: 1.0
nome_unico_corrigido | soma média: 1.0
multiplas_expressoes | soma média: 1.0
multiplas_expressoes_corrigidas | soma média: 1.0
Artigo: 51 | classes reais: math.CO, cs.DM

                 nome_unico  ...  multiplas_expressoes_corrigidas
cs.MA              0.000041  ...                         0.286552
cond-mat.dis-nn    0.689431  ...                         0.141080
math.ST            0.003451  ...                         0.072240
cmp-lg             0.114238  ...                         0.068432
cs.GT              0.062297  ...                         0.060889
cs.CC              0.063597  ...                         0.049170
cs.SI              0.000015  ...                         0.039352
math.CO            0.000152  ...                         0.031069
cs.CR              0.001440  ...                         0.028730
cs.PF              0.000007  ...                         0.025334
math.OC            0.001297  ...                         0.023251
cs.IR              0.000018  ...                         0.019885

[12 rows x 4 columns]

## 4. Escolha da correção e avaliação exploratória

LRAP é o critério principal de ranking por documento. Ranking loss e coverage error devem ser menores. AP micro compara scores globalmente e é sensível à escala entre documentos. F1 micro/macro e Jaccard usam **top-3 fixo**, igual para as quatro variantes, sem consultar a quantidade real de rótulos de cada artigo.

As métricas abaixo usam apenas os 1.600 artigos de avaliação. O suporte das 54 classes é exportado, inclusive quando uma classe tem poucos exemplos em um split.

In [4]:
search = pd.read_csv(OUTPUT_DIR / 'busca_lambda_validacao.csv')
support = pd.read_csv(OUTPUT_DIR / 'suporte.csv')
display(search)
display(support)
px.line(search, x='lambda', y='LRAP validacao', color='multiplas_expressoes', markers=True,
        title='Força da correção escolhida apenas na validação').show()
selected = ['LRAP','Ranking loss','Acerto top1','F1 micro top3','F1 macro top3']
plot_data = metrics[['Metodo',*selected]].melt(id_vars='Metodo', var_name='Métrica', value_name='Valor')
fig = px.bar(plot_data, x='Metodo', y='Valor', color='Metodo', facet_col='Métrica', facet_col_wrap=3,
             title='Scores exatos: comparação em 1.600 artigos de avaliação')
fig.update_yaxes(matches=None)
fig.update_layout(height=650, showlegend=False)
fig.show()

   multiplas_expressoes  lambda  LRAP validacao
0                 False    0.00        0.198189
1                 False    0.25        0.219486
2                 False    0.50        0.242498
3                 False    0.75        0.256320
4                 False    1.00        0.255808
5                  True    0.00        0.223392
6                  True    0.25        0.256998
7                  True    0.50        0.301245
8                  True    0.75        0.336574
9                  True    1.00        0.345394

                Classe  Validacao  Avaliacao
0               cmp-lg          8         25
1      cond-mat.dis-nn          3         16
2   cond-mat.stat-mech          8         25
3                cs.AI         53        158
4                cs.CC         22         80
5                cs.CE         12         24
6                cs.CG          5         33
7                cs.CL         20         79
8                cs.CR         15         83
9                cs.CV         15         80
10               cs.CY         10         51
11               cs.DB         10         39
12               cs.DC         17         57
13               cs.DL         11         20
14               cs.DM         22        115
15               cs.DS         31        130
16               cs.FL         10         27
17               cs.GT         10         54
18               cs.HC          6         22
19               cs.IR         23         54
20               cs.IT        136        547
21               cs.LG         55        239
22               cs.LO         20        112
23               cs.MA          8         31
24               cs.MM          5         23
25               cs.MS          7          5
26               cs.NA          9         30
27               cs.NE         17         63
28               cs.NI         20         86
29               cs.PF          5         24
30               cs.PL         13         46
31               cs.RO          5         29
32               cs.SC          0         19
33               cs.SE         12         36
34               cs.SI         23        111
35               cs.SY         18         54
36             math.CO         22         97
37             math.IT        136        547
38             math.LO          5         21
39             math.NA          9         28
40             math.NT          0          9
41             math.OC         20         82
42             math.PR         12         23
43             math.ST         12         24
44             nlin.AO          2         12
45     physics.data-an          1         15
46      physics.soc-ph         18         95
47            q-bio.NC          2         11
48            q-bio.QM          1         10
49            quant-ph         16         45
50             stat.AP          4         17
51             stat.ME          4          9
52             stat.ML         34        151
53             stat.TH         12         24

Gráfico interativo: comparação dos métodos

Gráfico interativo: comparação dos métodos

## 5. Inspecionar viés, comprimento e diferenças por classe

Expressões com alta probabilidade na referência podem receber scores altos mesmo sem evidência específica do artigo. A correção testa se descontar essa preferência melhora a classificação. O gráfico de comprimento é um diagnóstico descritivo, não prova causal de viés.

Compare também classes favorecidas e prejudicadas: uma melhora global pode esconder perdas em classes raras.

In [5]:
from scipy.special import logsumexp
with np.load(OUTPUT_DIR / 'checkpoint.npz') as checkpoint:
    reference_logp = checkpoint['references']
    raw_logp = checkpoint['logp']
prior = logsumexp(reference_logp, axis=0) - np.log(len(REFERENCES))
catalog = pd.read_csv(OUTPUT_DIR / 'verbalizadores.csv')
catalog['Log probabilidade neutra'] = prior
catalog['Log probabilidade média nos artigos'] = raw_logp.mean(0)
display(catalog.sort_values('Log probabilidade neutra', ascending=False).head(20))
px.scatter(catalog, x='Tokens incluindo EOS', y='Log probabilidade neutra',
           hover_name='Expressao', color='Variante', title='Comprimento e preferência nas entradas neutras').show()
class_table = per_class.pivot(index='Classe', columns='Metodo', values='F1')
class_table['Ganho multi corrigido vs único'] = class_table['multiplas_expressoes_corrigidas'] - class_table['nome_unico']
display(class_table.sort_values('Ganho multi corrigido vs único', ascending=False))
px.bar(per_class, x='Classe', y='F1', color='Metodo', barmode='group', hover_data=['Suporte avaliacao'],
       title='F1 por classe na avaliação exploratória', height=550).show()

                 Classe  ...  Log probabilidade média nos artigos
23                cs.CL  ...                            -5.986510
7    cond-mat.stat-mech  ...                            -6.453455
17                cs.CE  ...                            -7.454441
16                cs.CE  ...                            -9.185552
22                cs.CL  ...                            -5.853638
63                cs.LG  ...                            -5.254262
51                cs.GT  ...                            -4.465305
3       cond-mat.dis-nn  ...                            -3.525933
142            q-bio.NC  ...                            -9.897750
10                cs.AI  ...                            -7.419003
47                cs.DS  ...                            -5.996722
81                cs.NE  ...                            -6.392031
4       cond-mat.dis-nn  ...                            -3.405588
24                cs.CR  ...                            -7.927413
42                cs.DM  ...                            -6.222510
9                 cs.AI  ...                            -6.132113
151             stat.AP  ...                            -8.411120
60                cs.IT  ...                            -8.506899
157             stat.ML  ...                            -8.468968
12                cs.CC  ...                            -6.808274

[20 rows x 6 columns]

Gráfico interativo: comparação dos métodos

Metodo              multiplas_expressoes  ...  Ganho multi corrigido vs único
Classe                                    ...
physics.soc-ph                  0.100000  ...                        0.655367
quant-ph                        0.043478  ...                        0.619718
math.IT                         0.007273  ...                        0.529538
cs.CG                           0.190476  ...                        0.377778
math.LO                         0.160000  ...                        0.375000
cs.DC                           0.032258  ...                        0.319328
cs.DB                           0.217391  ...                        0.292471
cs.CR                           0.452055  ...                        0.291333
math.OC                         0.102041  ...                        0.285714
cs.PL                           0.150943  ...                        0.270696
cs.FL                           0.000000  ...                        0.268293
cs.SI                           0.236220  ...                        0.263589
math.CO                         0.040000  ...                        0.249834
cs.SY                           0.000000  ...                        0.243590
cs.CY                           0.128205  ...                        0.206865
cs.NI                           0.022727  ...                        0.199234
stat.ML                         0.433628  ...                        0.177019
cs.SE                           0.054054  ...                        0.167464
cs.PF                           0.080000  ...                        0.135385
cmp-lg                          0.091837  ...                        0.128137
nlin.AO                         0.000000  ...                        0.121212
q-bio.NC                        0.266667  ...                        0.100000
math.ST                         0.000000  ...                        0.090327
cs.SC                           0.095238  ...                        0.089636
math.NA                         0.000000  ...                        0.088889
cs.HC                           0.000000  ...                        0.083333
cs.CE                           0.222222  ...                        0.080000
cs.MA                           0.000000  ...                        0.057870
cs.IR                           0.071429  ...                        0.055508
cs.MM                           0.000000  ...                        0.053476
cs.CL                           0.345972  ...                        0.049383
cs.GT                           0.071842  ...                        0.039427
cs.DS                           0.200000  ...                        0.035955
cond-mat.dis-nn                 0.022615  ...                        0.015920
stat.ME                         0.000000  ...                        0.000000
q-bio.QM                        0.000000  ...                        0.000000
math.PR                         0.000000  ...                        0.000000
cs.DL                           0.000000  ...                        0.000000
stat.TH                         0.000000  ...                        0.000000
stat.AP                         0.000000  ...                        0.000000
physics.data-an                 0.000000  ...                        0.000000
cond-mat.stat-mech              0.116592  ...                       -0.028169
cs.CV                           0.492063  ...                       -0.035631
cs.DM                           0.137500  ...                       -0.046737
cs.NA                           0.000000  ...                       -0.049770
cs.IT                           0.063604  ...                       -0.052382
cs.RO                           0.162162  ...                       -0.060876
cs.NE                           0.097297  ...                       -0.075204
cs.LO                           0.251852  ...                       -0.092105
math.NT                         0.307692  ...                       -0.112821
cs.CC                           0.276923  ...                       -0.140329
cs.AI                           0.178988  ...                       -0.157576
cs.LG                           0.544144  ...                       -0.229788
cs.MS                           0.285714  ...                       -0.250000

[54 rows x 5 columns]

Gráfico interativo: comparação dos métodos

## 6. Conclusão calculada e próximos passos

Escolher o melhor LRAP observado serve para orientar a próxima rodada, não para provar superioridade. Revisões dos verbalizadores, lambda e templates devem ser tratadas como desenvolvimento. A contribuição candidata está na combinação e avaliação dos componentes; pontuar nomes, usar verbalizadores e corrigir viés já têm antecedentes na literatura.

Próximos testes: estabilidade diante de ordem/templates, comparação com modelo maior, calibração de pertinência independente por classe e avaliação final em documentos ainda não inspecionados.

In [6]:
best = metrics.loc[metrics.LRAP.idxmax()]
print(f"Maior LRAP exploratório: {best['Metodo']} ({best['LRAP']:.4f}).")
print('Lambdas selecionados:')
display(metrics[['Metodo','lambda']])
print('Scores completos e distribuições relativas salvos em:', OUTPUT_DIR)
display(pd.DataFrame({'Arquivo': sorted(p.name for p in OUTPUT_DIR.iterdir() if p.is_file())}))

Maior LRAP exploratório: multiplas_expressoes_corrigidas (0.3556).
Lambdas selecionados:
Scores completos e distribuições relativas salvos em: /home/jesus/Documentos/LLDA/experimento_classificacao_topicos/resultados/llda_scores_exatos_54

                            Metodo  lambda
0                       nome_unico    0.00
1             nome_unico_corrigido    0.75
2             multiplas_expressoes    0.00
3  multiplas_expressoes_corrigidas    1.00

                                                      Arquivo
0                                  busca_lambda_validacao.csv
1                                              checkpoint.npz
2                                           configuracao.json
3              distribuicao_relativa_multiplas_expressoes.csv
4   distribuicao_relativa_multiplas_expressoes_corrigidas.csv
5                        distribuicao_relativa_nome_unico.csv
6              distribuicao_relativa_nome_unico_corrigido.csv
7                                              documentos.csv
8                                           execucao_gpu.json
9                                             logp_brutos.csv
10                                       logp_referencias.csv
11                                     metricas_avaliacao.csv
12                                    metricas_por_classe.csv
13                            scores_multiplas_expressoes.csv
14                 scores_multiplas_expressoes_corrigidas.csv
15                                      scores_nome_unico.csv
16                            scores_nome_unico_corrigido.csv
17                                                  split.csv
18                                                suporte.csv
19                                         verbalizadores.csv

Referências relacionadas: [verbalizadores em classificação de tópicos](https://aclanthology.org/2024.lrec-main.527/), [correção de vieses de rótulos](https://aclanthology.org/2023.acl-long.783/). Este notebook é uma exploração metodológica, não uma alegação de novidade estabelecida.

## Resultado desta execução

Qwen2.5-0.5B-Instruct na RTX 5080: **324.000 scores de candidatos** nos 2.000 artigos, além das três referências neutras. Inferência e checkpoint: **259,86 segundos**; pico de memória CUDA alocada: **1,71 GiB**.

| Variante | Lambda escolhido na validação | LRAP na avaliação | Acerto top-1 |
|---|---:|---:|---:|
| Nome único | 0 | 0,2148 | 12,19% |
| Nome único corrigido | 0,75 | 0,2684 | 21,19% |
| Múltiplas expressões | 0 | 0,2341 | 13,62% |
| Múltiplas expressões corrigidas | 1 | 0,3556 | 37,38% |

Nesta avaliação exploratória, a combinação apresentou a maior recuperação dos rótulos. O resultado apoia investigar a correção da preferência lexical, mas não estabelece calibração nem superioridade em dados novos. Há quatro distribuições relativas por artigo, com 54 componentes e soma 1, e os scores anteriores à normalização foram preservados.