# LLDA trie_beams: 2.000 artigos, 54 classes e execução em GPU

Expandimos o ensaio de cinco artigos para o conjunto completo. A LLM recebe o resumo e o catálogo fixo de **54 nomes legíveis**; uma árvore de prefixos permite gerar somente esses nomes. Cada documento retorna quatro hipóteses de beam search.

**O que mudou:** resumos completos, todas as classes, processamento em lotes CUDA e checkpoint após cada lote. Os códigos originais são preservados. Classes próximas recebem qualificadores, por exemplo **Information Theory (Computer Science)** e **Information Theory (Mathematics)**, para manter 54 saídas distintas.

Os rótulos reais servem para conferir a recuperação dos textos e avaliar as respostas; não entram no prompt nem na escolha dos tokens. LLDA aqui é o método por LLM do projeto, não Labeled LDA.

In [1]:
from pathlib import Path
import sys
import json
import pandas as pd
import torch
from IPython.display import display
import plotly.express as px

ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / 'dataset_loader.py').exists())
EXPERIMENT_DIR = ROOT / 'experimento_classificacao_topicos'
sys.path.insert(0, str(EXPERIMENT_DIR))
from llda_trie_54 import CLASSES, LABELS, full_dataset, require_gpu, run_gpu

pd.set_option('display.max_colwidth', 100)
df = full_dataset()
print(f'{len(df)} documentos completos; {len(CLASSES)} classes; IDs originais preservados')
display(pd.DataFrame({'Classe': CLASSES, 'Nome para LLM': LABELS}))
display(df[['doc_id', 'fonte_texto', 'classes_reais_aapd']].head())
print('Caracteres por resumo:', df.resumo_texto.str.len().describe().round(1).to_dict())

2000 documentos completos; 54 classes; IDs originais preservados
Caracteres por resumo: {'count': 2000.0, 'mean': 985.1, 'std': 394.3, 'min': 37.0, '25%': 703.8, '50%': 951.0, '75%': 1235.0, 'max': 3132.0}

                Classe                                              Nome para LLM
0               cmp-lg                 Computation and Language (Legacy Category)
1      cond-mat.dis-nn                     Disordered systems and neural networks
2   cond-mat.stat-mech                                      Statistical mechanics
3                cs.AI                                    Artificial intelligence
4                cs.CC                                   Computational complexity
5                cs.CE              Computational engineering finance and science
6                cs.CG                                     Computational geometry
7                cs.CL  Computational linguistics and natural language processing
8                cs.CR                                  Cryptography and security
9                cs.CV                    Computer vision and pattern recognition
10               cs.CY                                      Computers and society
11               cs.DB                                                  Databases
12               cs.DC                 Distributed parallel and cluster computing
13               cs.DL                                          Digital libraries
14               cs.DM                                       Discrete mathematics
15               cs.DS                             Data structures and algorithms
16               cs.FL                       Formal languages and automata theory
17               cs.GT                           Computer science and game theory
18               cs.HC                                 Human computer interaction
19               cs.IR                                      Information retrieval
20               cs.IT                      Information Theory (Computer Science)
21               cs.LG                                           Machine learning
22               cs.LO                                  Logic in computer science
23               cs.MA                                         Multiagent systems
24               cs.MM                                                 Multimedia
25               cs.MS                                      Mathematical software
26               cs.NA                      Numerical Analysis (Computer Science)
27               cs.NE                          Neural and evolutionary computing
28               cs.NI                       Networking and internet architecture
29               cs.PF                                       Computer performance
30               cs.PL                                      Programming languages
31               cs.RO                                                   Robotics
32               cs.SC                                       Symbolic computation
33               cs.SE                                       Software engineering
34               cs.SI                            Social and information networks
35               cs.SY                                        Systems and control
36             math.CO                                              Combinatorics
37             math.IT                           Information Theory (Mathematics)
38             math.LO                                         Mathematical logic
39             math.NA                           Numerical Analysis (Mathematics)
40             math.NT                                              Number theory
41             math.OC                                   Optimization and control
42             math.PR                                                Probability
43             math.ST                            Statistics Theory (Mathematics)
44             nlin.AO                     Adaptation and self organizing systems
45     physics.data-an                   Data analysis statistics and probability
46      physics.soc-ph                                        Physics and society
47            q-bio.NC                                      Neurons and cognition
48            q-bio.QM                            Quantitative methods in biology
49            quant-ph                                            Quantum physics
50             stat.AP                                    Statistics applications
51             stat.ME                                     Statistics methodology
52             stat.ML                               Statistical machine learning
53             stat.TH                             Statistics Theory (Statistics)

   doc_id          fonte_texto     classes_reais_aapd
0      51   test.txt:artigo_51         math.CO, cs.DM
1     178  test.txt:artigo_178  physics.soc-ph, cs.DL
2     209  test.txt:artigo_209  cs.SI, physics.soc-ph
3     228  test.txt:artigo_228         cs.IT, math.IT
4     285  test.txt:artigo_285           cs.DC, cs.DS

## 1. Configurar a GPU e o decoding

Mantemos **Qwen2.5-0.5B-Instruct** para comparar com o ensaio anterior. A GPU acelera lotes de oito documentos, cada um com quatro beams. O código exige CUDA e não muda silenciosamente para CPU.

O score do beam usa penalização por comprimento; não representa probabilidade calibrada de uma classe. Os beams são hipóteses de sequência, não amostras independentes. Usamos os três primeiros para a avaliação multi-rótulo, sem consultar quantas classes reais cada artigo possui.

In [2]:
MODEL_NAME = 'Qwen/Qwen2.5-0.5B-Instruct'
BATCH_SIZE = 8
NUM_BEAMS = 4
TOP_K = 3
LOCAL_FILES_ONLY = False
CACHE_DIR = None  # opcional: cache do modelo
OUTPUT_DIR = EXPERIMENT_DIR / 'resultados' / 'llda_trie_54_gpu'

gpu = require_gpu()
print(f"GPU: {gpu['name']} | VRAM livre: {gpu['free_bytes'] / 1024**3:.2f} GiB")

GPU: NVIDIA GeForce RTX 5080 | VRAM livre: 14.65 GiB

## 2. Executar com restrição por trie

O callback `prefix_allowed_tokens_fn` consulta a árvore após cada token. EOS só é permitido ao completar um nome. O limite de geração cobre o nome tokenizado mais longo e o EOS. Todas as saídas são validadas por igualdade exata.

Agrupamos textos de comprimentos próximos para reduzir padding e usamos padding à esquerda, apropriado para geração causal em lotes. O checkpoint é substituído atomicamente após cada lote. Ao repetir a célula, documentos concluídos são reutilizados; parâmetros ou dados diferentes exigem outra pasta de resultados.

O CSV comparativo guarda apenas o começo dos resumos. Recuperamos os textos completos nos arquivos locais AAPD por prefixo e classes; não truncamos os artigos para a geração.

In [3]:
df, outputs, metrics, per_class = run_gpu(
    output_dir=OUTPUT_DIR, model_name=MODEL_NAME, batch_size=BATCH_SIZE,
    num_beams=NUM_BEAMS, top_k=TOP_K, cache_dir=CACHE_DIR,
    local_files_only=LOCAL_FILES_ONLY,
)
display(metrics.round(4))

GPU: NVIDIA GeForce RTX 5080; 2000 artigos; 2000 concluídos; 0 pendentes
 documentos  classes  validade_exata  acerto_top1  precisao_top3  recall_top3  F1 micro  F1 macro (54)  Jaccard
       2000       54             1.0       0.1595         0.1608       0.1792    0.1694         0.1177   0.1124

   documentos  classes  validade_exata  ...  F1 micro  F1 macro (54)  Jaccard
0        2000       54             1.0  ...    0.1694         0.1177   0.1124

[1 rows x 9 columns]

## 3. Inspecionar as atribuições

Cada beam produz um nome legível e seu código de classe. Conformidade com o catálogo não garante acerto semântico. Pares de categorias equivalentes ou coocorrentes, como `cs.IT`/`math.IT`, continuam difíceis de distinguir pelo conteúdo.

In [4]:
display(outputs.merge(df[['doc_id', 'classes_reais_aapd']], on='doc_id', validate='many_to_one').head(24))
print('Documentos concluídos:', outputs.doc_id.nunique())
print('Nomes fora do catálogo:', (~outputs.topico.isin(LABELS)).sum())
execution_file = OUTPUT_DIR / 'execucao_gpu.json'
if execution_file.exists():
    display(pd.DataFrame([json.loads(execution_file.read_text())]))

Documentos concluídos: 2000
Nomes fora do catálogo: 0

    doc_id  rank  ... valido   classes_reais_aapd
0        7     1  ...   True         cs.GT, cs.NI
1        7     2  ...   True         cs.GT, cs.NI
2        7     3  ...   True         cs.GT, cs.NI
3        7     4  ...   True         cs.GT, cs.NI
4     1754     1  ...   True         cs.AI, cs.NE
5     1754     2  ...   True         cs.AI, cs.NE
6     1754     3  ...   True         cs.AI, cs.NE
7     1754     4  ...   True         cs.AI, cs.NE
8      259     1  ...   True       cs.IT, math.IT
9      259     2  ...   True       cs.IT, math.IT
10     259     3  ...   True       cs.IT, math.IT
11     259     4  ...   True       cs.IT, math.IT
12    1050     1  ...   True  cs.AI, cs.LG, cs.RO
13    1050     2  ...   True  cs.AI, cs.LG, cs.RO
14    1050     3  ...   True  cs.AI, cs.LG, cs.RO
15    1050     4  ...   True  cs.AI, cs.LG, cs.RO
16    1938     1  ...   True         cs.CC, cs.DM
17    1938     2  ...   True         cs.CC, cs.DM
18    1938     3  ...   True         cs.CC, cs.DM
19    1938     4  ...   True         cs.CC, cs.DM
20     319     1  ...   True       cs.IT, math.IT
21     319     2  ...   True       cs.IT, math.IT
22     319     3  ...   True       cs.IT, math.IT
23     319     4  ...   True       cs.IT, math.IT

[24 rows x 7 columns]

                       gpu  ...  vram_pico_gib
0  NVIDIA GeForce RTX 5080  ...       2.305996

[1 rows x 4 columns]

## 4. Recuperação das classes originais

Acerto top-1 aceita qualquer classe verdadeira. Precisão e recall top-3 comparam os três primeiros nomes distintos com o conjunto de rótulos reais; F1 micro/macro e Jaccard avaliam as mesmas atribuições. O F1 macro mantém as 54 classes, inclusive as raras.

Não calculamos LRAP do ranking completo: quatro beams não fornecem os scores de todas as 54 classes. Os resultados descrevem a classificação desses 2.000 artigos; não houve treinamento nem ajuste de parâmetros usando seus rótulos.

In [5]:
display(per_class.sort_values('F1', ascending=False))
px.bar(per_class, x='Classe', y='F1', hover_data=['Nome', 'Suporte', 'Precisão', 'Recall'],
       title='LLDA trie_beams — F1 por classe original (top-3)', height=550).show()
px.scatter(per_class, x='Suporte', y='F1', hover_name='Classe', hover_data=['Nome'],
           title='Suporte da classe e qualidade das atribuições').show()

                Classe  ... Suporte
21               cs.LG  ...     294
22               cs.LO  ...     132
40             math.NT  ...       9
49            quant-ph  ...      61
34               cs.SI  ...     134
52             stat.ML  ...     185
20               cs.IT  ...     683
19               cs.IR  ...      77
41             math.OC  ...     102
3                cs.AI  ...     211
8                cs.CR  ...      98
4                cs.CC  ...     102
32               cs.SC  ...      19
9                cs.CV  ...      95
30               cs.PL  ...      59
15               cs.DS  ...     161
6                cs.CG  ...      38
27               cs.NE  ...      80
38             math.LO  ...      26
36             math.CO  ...     119
18               cs.HC  ...      28
33               cs.SE  ...      48
47            q-bio.NC  ...      13
53             stat.TH  ...      36
14               cs.DM  ...     137
12               cs.DC  ...      74
37             math.IT  ...     683
5                cs.CE  ...      36
17               cs.GT  ...      64
29               cs.PF  ...      29
31               cs.RO  ...      34
2   cond-mat.stat-mech  ...      33
26               cs.NA  ...      39
23               cs.MA  ...      39
10               cs.CY  ...      61
25               cs.MS  ...      12
43             math.ST  ...      36
11               cs.DB  ...      49
51             stat.ME  ...      13
16               cs.FL  ...      37
7                cs.CL  ...      99
0               cmp-lg  ...      33
1      cond-mat.dis-nn  ...      19
13               cs.DL  ...      31
24               cs.MM  ...      28
28               cs.NI  ...     106
35               cs.SY  ...      72
44             nlin.AO  ...      14
42             math.PR  ...      35
39             math.NA  ...      37
45     physics.data-an  ...      16
46      physics.soc-ph  ...     113
48            q-bio.QM  ...      11
50             stat.AP  ...      21

[54 rows x 6 columns]

Gráfico interativo: comparação dos métodos

Gráfico interativo: comparação dos métodos

## 5. Arquivos e próximas comparações

A pasta de resultados contém textos completos e suas fontes, catálogo, outputs, métricas gerais e por classe, configuração, revisão do modelo, tempo de execução e pico de VRAM. O notebook usa checkpoints para permitir retomada sem repetir todo o corpus.

Próximas comparações: variar o número de beams, testar um modelo maior e comparar com Seeded LDA/Guided BERTopic usando os mesmos **textos completos**. Os experimentos anteriores que leram diretamente `resumo_texto` do CSV usaram fragmentos e não são uma comparação equivalente de entrada.

In [6]:
print(f'Resultados: {OUTPUT_DIR}')
display(pd.DataFrame({'Arquivo': sorted(p.name for p in OUTPUT_DIR.iterdir() if p.is_file())}))

Resultados: /home/jesus/Documentos/LLDA/experimento_classificacao_topicos/resultados/llda_trie_54_gpu

                   Arquivo
0    artigos_completos.csv
1             catalogo.csv
2        configuracao.json
3        execucao_gpu.json
4             metricas.csv
5  metricas_por_classe.csv
6              outputs.csv

## Resultado da execução na RTX 5080

Com Qwen2.5-0.5B-Instruct, lotes de 8 e quatro beams por documento:

- **2.000 artigos concluídos**, com 8.000 hipóteses e validade exata de 100%.
- **Acerto top-1: 15,95%**; F1 micro top-3: 0,1694; F1 macro: 0,1177.
- Inferência e checkpoint dos lotes: **68,33 segundos**, excluindo preparação/carregamento; pico de memória CUDA alocada: **2,31 GiB**.

A restrição funcionou para todas as respostas. A baixa recuperação das classes mostra que controlar o formato não resolve sozinho a classificação; a próxima comparação pode usar um modelo maior e revisar os nomes das categorias.